### PR TITLE
finish fix content encoding problem with non-utf8 char

### LINKED ISSUE #5: Problem on feed_entry when its encoding is not utf-8.
There is an error when showing the feed_entry, if the feed_entry's content is not in utf-8 encodin.

### PR DESCRIPTION
**Pull request by Thyda-Eng**
Fixes #5 .

### CODE REVIEW

File: spec/models/fetch_page_spec.rb [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+      it "does not set charset" do
+        result = FetchPage.instance.run("http://www.cdc.gov/ecoli/2009/")
+        expect(result).to include('utf-8')
+      end
+    end
+  end
+
+  describe ".identify_encoding_type" do
+    context "with utf-8 charset" do
+      context "when charset is the property of meta tag" do
```
Comment (kakada) [inline spec/models/fetch_page_spec.rb:26]: should apply gem 'vcr' for fetching the content of HTTP request http://www.cdc.gov/ecoli/2009/ so it will make the spec much faster

File: spec/models/fetch_page_spec.rb [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+    context "when meta tag has charset different from utf-8" do
+      it "does not set charset" do
+        result = FetchPage.instance.run("http://www.cdc.gov/ecoli/2009/")
+        expect(result).to include('utf-8')
+      end
+    end
+  end
+
+  describe ".identify_encoding_type" do
+    context "with utf-8 charset" do
```
Comment (kakada) [inline spec/models/fetch_page_spec.rb:25]: should apply gem 'vcr' for fetching the content of HTTP request http://www.cdc.gov/ecoli/2009/ so it will make the spec much faster

File: spec/models/fetch_page_spec.rb [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+
+    context "when meta tag has charset different from utf-8" do
+      it "does not set charset" do
+        result = FetchPage.instance.run("http://www.cdc.gov/ecoli/2009/")
+        expect(result).to include('utf-8')
+      end
+    end
+  end
+
+  describe ".identify_encoding_type" do
```
Comment (kakada) [inline spec/models/fetch_page_spec.rb:24]: should apply gem 'vcr' for fetching the content of HTTP request http://www.cdc.gov/ecoli/2009/ so it will make the spec much faster
